webRestaurante/blog/urls.py
from django.urls import path
from blog.views import PostListView, CategoryPageView

post_urlpatterns = ([
    path('', PostListView.as_view(), name='post_list'),
    # path('category/<int:category_id>', views.category, name='category')
    path('category/<int:category_id>', CategoryPageView.as_view(), name='category')
], 'posts')

webRestaurante/core/urls.py
from django.urls import path
from core import views
from core.views import HomePageView

core_urlpatterns = ([
    #path('', views.home, name='home'),
    path('', HomePageView.as_view(), name='home'),
    path('historia/', views.historia, name='historia'),
    path('visit/', views.visit, name='visit'),
], 'core')

webRestaurante/webRestaurante/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from core.urls import core_urlpatterns
from services.urls import service_urlpatterns
from recipes.urls import recipe_urlpatterns
from blog.urls import post_urlpatterns
from pages.urls import page_urlpatterns
from contact.urls import contact_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(core_urlpatterns)),
    path('services/', include(service_urlpatterns)),
    path('recipes/', include(recipe_urlpatterns)),
    path('posts/', include(post_urlpatterns)),
    path('pages/', include(page_urlpatterns)),
    path('contact/', include(contact_urlpatterns)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

webRestaurante/core/models.py
from django.db import models

# Create your models here.

webRestaurante/pages/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Page(models.Model):
    title = models.CharField(max_length=200, verbose_name="Titulo")
    content = RichTextField(verbose_name="Contenido")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de edición")

    class Meta:
        verbose_name = "Pagina"
        verbose_name_plural = "Paginas"
        ordering = ['title']

    def __str__(self):
        return self.title

webRestaurante/recipes/models.py
from django.db import models

# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=200, verbose_name='Titulo')
    subtitle = models.CharField(max_length=200, verbose_name='Subititulo')
    content = models.TextField(verbose_name='Contenido')
    image = models.ImageField(verbose_name='Imagen', upload_to='services')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')

    class Meta:
        verbose_name = 'receta'
        verbose_name_plural = 'recetas'
        ordering = ['-created']

    def __str__(self):
        return self.title

webRestaurante/services/models.py
from django.db import models


# Create your models here.
class Service(models.Model):
    title = models.CharField(max_length=200, verbose_name='Titulo')
    subtitle = models.CharField(max_length=200, verbose_name='Subtitulo')
    content = models.TextField(verbose_name='Contenido')
    image = models.ImageField(verbose_name='Imagen', upload_to='services')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')
    updated = models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion')

    class Meta:
        verbose_name = 'servicio'
        verbose_name_plural = 'servicios'
        ordering = ['-created']

    def __str__(self):
        return self.title

webRestaurante/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView


class HomePageView(TemplateView):
    template_name = 'core/home.html'



# Create your views here.
# def home(request):
#     return render(request, 'core/home.html')

def historia(request):
    return render(request, 'core/historia.html')

def visit(request):
    return render(request, 'core/visit.html')

webRestaurante/core/templates/core/base.html
<!DOCTYPE html>
<html lang="es">
<!-- digital color -->

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS v5.0.2 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <!-- font awesome CSS v5.10.0 -->
  <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
    integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

  <!-- JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
  </script>
    {% load static %}
  <title>Inicio | La Recova</title>

  <!-- Estilos -->
  <link href="{% static 'core/css/business-casual.css' %}" rel="stylesheet">
</head>

<body>

  <h1 class="site-heading text-center text-white d-none d-lg-block">
    <span class="site-heading-upper text-primary mb-3">El auténtico sabor argentino</span>
    <span class="site-heading-lower">La Recova</span>
  </h1>

  <!-- Navegación -->
  <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">La Recova</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
        aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item {% if request.path == '/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'core:home' %}">Inicio</a>
          </li>
          <li class="nav-item {% if request.path == '/historia/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'core:historia' %}">Historia</a>
          </li>
          <li class="nav-item {% if request.path == '/services/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'service:service_list' %}">Servicios</a>
          </li>
          <li class="nav-item {% if request.path == '/visit/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'core:visit' %}">Visítanos</a>
          </li>
          <li class="nav-item {% if request.path == '/visit/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'contact:contact' %}">Contacto</a>
          </li>
          <li class="nav-item {% if request.path|slice:':7' == '/posts/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'posts:post_list' %}">Blog</a>
          </li>
          <li class="nav-item {% if request.path == '/recipes/' %}active{% endif %} px-lg-4">
            <a class="nav-link text-uppercase text-expanded" href="{% url 'recipe:recipe_list' %}">Recetas</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% block content %}
{% endblock %}


  <!-- Pié de página -->
  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0">
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
          </span>
        </a>
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-facebook fa-stack-1x fa-inverse"></i>
          </span>
        </a>
        <a href="#" class="link">
          <span class="fa-stack fa-lg">
            <i class="fa fa-circle fa-stack-2x"></i>
            <i class="fab fa-instagram fa-stack-1x fa-inverse"></i>
          </span>
        </a>
      </p>
      <p class="m-0 mbt">
        {% load page_extras %}
        {% get_page_list as page_list %}
        {% for page in page_list %}
          <a href="{% url 'pages:page' page.id %}" class="link">{{ page.title }}</a>
          {% if not forloop.last %}·{% endif %}
        {% endfor %}
      </p>
      <p class="m-0 mbt1">&copy; La Recova <span id="year"></span></p>
    </div>
  </footer>
  <!-- Bootstrap JavaScript Libraries -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

  <script>
    // Get the current year for the copyright
    $("#year").text(new Date().getFullYear());
  </script>
</body>

</html>

webRestaurante/core/templates/core/historia.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}

  <section class="page-section about-heading">
    <div class="container">
      <img class="img-fluid rounded about-heading-img mb-3 mb-lg-0" src="{% static 'core/img/about.jpg'%}" alt="">
      <div class="about-heading-content">
        <div class="row">
          <div class="col-xl-9 col-lg-10 mx-auto">
            <div class="bg-faded rounded p-5">
              <h2 class="section-heading mb-4">
                <span class="section-heading-upper">Tradición familiar argentina</span>
                <span class="section-heading-lower">Nuestra historia</span>
              </h2>
              <p>Fundada en 1973 consectetur adipiscing elit. Donec leo dui, vehicula vel dapibus ac, tempus non enim.
                Nunc tempor vel lacus vel gravida. Nam sit amet pellentesque mi. </p>
              <p>Curabitur efficitur pellentesque tellus nec volutpat. In viverra mattis sem, facilisis condimentum mi
                rutrum ut. Quisque ut pellentesque dui.Nullam eu vehicula metus. Pellentesque id interdum elit. Aenean
                in efficitur enim.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

webRestaurante/core/templates/core/home.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}

  <!-- Cabecera -->
  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'core/img/intro.jpg'%}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Déjate sorprender</span>
            <span class="section-heading-lower">Te gustará</span>
          </h2>
          <p class="mb-3">Trabajamos sólo con los mejores ingredientes. Una vez que pruebes nuestros cortes será la
            mejor experiencia culinaria.
          </p>
          <div class="intro-button mx-auto">
            <a class="btn btn-primary btn-xl" href="#">Visítanos</a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- Mensaje -->
  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">Compromiso total</span>
              <span class="section-heading-lower">Garantizado</span>
            </h2>
            <p class="mb-0">Sed pulvinar blandit elit id venenatis. Ut eget lacus neque. Nullam justo quam, efficitur
              nec turpis vitae, efficitur posuere ligula. Proin ut turpis orci. Aenean porta sodales lectus faucibus
              pellentesque. In sed felis iaculis, rhoncus felis a, maximus mi.</p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

webRestaurante/core/templates/core/visit.html
{% extends 'core/base.html' %}
{% block content %}
{% load static %}

<section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-5">
              <span class="section-heading-upper">Te esperamos</span>
              <span class="section-heading-lower">Visítanos</span>
            </h2>
            <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
              <li class="list-unstyled-item list-hours-item d-flex">
                Martes a viernes
                <span class="ml-auto"> 13:00 a 23:30</span>
              </li>
              <li class="list-unstyled-item list-hours-item d-flex">
                Sábados y Domingos
                <span class="ml-auto"> 12:00 a 23:30</span>
              </li>
              <li class="list-unstyled-item list-hours-item d-flex">
                Lunes
                <span class="ml-auto"> Cerrado</span>
              </li>
            </ul>
            <p class="address mb-5">
              <em>
                <strong>Paseo de la reforma nº 127</strong>
                <br>
                CDMX
              </em>
            </p>
            <p class="mb-0">
              <small>
                <em>Llámanos y pregunta</em>
              </small>
              <br>
              (55) 5543-8778
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}